name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libatlas-base-dev
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  build_image:
    runs-on: ubuntu-latest
    needs: test
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo pip3 install docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d
